### ISSUE TITLE
Add support for upcoming ELF format

### ISSUE THREAD

**Issue by th-otto** [freemint/mintbin#3]
I was to lazy do fork & create this repo to create a branch so i'm just attaching the patch here ;)

It's almost identical to Vincent's patch, except that i slightly modified the check for 'ELF(' in the reserved field, using the last byte as offset for ELF header. This way, it should work both with the current layout, and any future extension when we need to enlarge that header.

[0001-Add-support-for-upcoming-ELF-format.patch.txt](https://github.com/freemint/mintbin/files/12386428/0001-Add-suppport-for-upcoming-ELF-format.patch.txt)

**Comment by mikrosk** [comment]
Resolved by https://github.com/freemint/mintbin/commit/3fee749daa55959dfb17c94f4c5922e3547a8238.
